title: Junge Pfarre Baden St. Stephan
description: >
  Suchst du nach einer coolen, jungen Gemeinschaft im Herzen Badens?
  Auf der Webseite der Jungen Pfarre Baden St. Stephan
  findest du unsere aktuellen Termine, Fotos von unseren
  Veranstaltungen und Infos Ã¼ber unsere Gemeinschaft aus
  Jugendlichen und jungen Erwachsenen.
short_description: Termine und Fotos der Jungen Pfarre
email: jugend@baden-st-stephan.at

lang: de_DE

collections:
- flyer

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown

plugins:
  - jekyll-coffeescript
  
repository: junge-pfarre/junge-pfarre.github.io

host: 0.0.0.0

theme: jekyll-theme-slate
